---
application:
  name: "wakeup-heroku"
  project: "wakeupheroku"
  organization: "QoveryCommunity"
routers:
- name: "main-wakeup-heroku"
  routes:
  - application_name: "wakeup-heroku"
    paths:
    - "/*"
